[workspace]
resolver = "2"

members = [
    "my_test",
    "hello_world",
    "guessing_game",
    "variables",
    "function_comment",
    "control_flow",
    "ownership",
    "reference_borrow",
    "slice",
    "struct_data",
    "struct_method"
]